BEGIN TRANSACTION;
DROP TABLE IF EXISTS mod_harobattle_haros;
DROP TABLE IF EXISTS mod_harobattle_betters;
DROP TABLE IF EXISTS mod_harobattle_data;
CREATE TABLE mod_harobattle_haros (id INTEGER PRIMARY KEY, name TEXT UNIQUE, color TEXT, precision INTEGER, dodge INTEGER, charisma INTEGER, armor INTEGER, hit_points INTEGER, weapon TEXT, power INTEGER, rouds_per_round INTEGER, time_to_reload INTEGER, rounds INTEGER);
CREATE TABLE mod_harobattle_betters (uuid TEXT PRIMARY KEY, wealth INTEGER);
CREATE TABLE mod_harobattle_data (key TEXT PRIMARY KEY, value TEXT);
INSERT INTO mod_harobattle_haros VALUES(1, 'vert',   'vert',   10, 5, 10, 3,  1, 'Fusil de sniper',     20, 1, 2,  4);
INSERT INTO mod_harobattle_haros VALUES(2, 'bleu',   'bleu',    6, 2, 4,  5, 10, 'L4z0r PewPew',        16, 3, 0, 15);
INSERT INTO mod_harobattle_haros VALUES(3, 'rose',   'rose',    8, 2, 7,  3, 15, 'Desert Eagle',        14, 1, 0, 10);
INSERT INTO mod_harobattle_haros VALUES(4, 'rouge',  'rouge',   9, 2, 1,  4, 12, 'Fusil à deux canons', 15, 2, 1, 16);
INSERT INTO mod_harobattle_haros VALUES(5, 'jaune',  'jaune',  10, 3, 10, 4, 12, 'Lance-flammes',        8, 2, 0, 20);
INSERT INTO mod_harobattle_haros VALUES(6, 'violet', 'violet',  9, 1, 5,  3, 20, 'Submachine Gun',      10, 2, 0, 18);
INSERT INTO mod_harobattle_haros VALUES(7, 'orange', 'orange',  6, 4, 2,  5, 14, 'M16',                 14, 2, 1, 30);
INSERT INTO mod_harobattle_haros VALUES(8, 'cyan',   'cyan',    7, 1, 1,  4, 16, 'MG42',                14, 3, 2, 30);

INSERT INTO mod_harobattle_data VALUES('champion_id',           '1');
INSERT INTO mod_harobattle_data VALUES('consecutive_victories', '1');
INSERT INTO mod_harobattle_data VALUES('pot',                   '0');
INSERT INTO mod_harobattle_data VALUES('reward',                '1');
COMMIT;
